### ISSUE TITLE
Site looks weird without JS

### ISSUE THREAD

**Issue by VehementHam** [Ultramarine-Linux/wiki#39]
Without JS, the sidebar is at the top, and main site content is below it. There is no margine to the left of the main content, and it looks weird. I have tested this in Netsurf.

Other than that, the site looks good. A possible fix would involve ensuring that the main content was to the right of the sidebar by using HTML/CSS.

If that doesn't work, then magin should be added to the left of the main content.

**Comment by VehementHam** [comment]
So I assume that we should give the sidebar a set width, then give the main content a margin of that width. You would also declare the sidebar `float-left`.

We shouldn't use JS to layout the site. 

I am not sure how this whole Astro thing works, but I will read the code, and try to figure out if this issue would be viable to solve.

**Comment by muhdsalm** [comment]
The site just looks blank to me. Is that the same for you?
If so, the easy way out would be to just put some text saying something like, "Please turn on Javascript to view this site".

**Comment by nothingneko** [comment]
As far as I'm aware this will not work at all without JS, it's more of a webapp than a traditional HTML document. I agree with muhd that we should add some text if JS is disabled, I'm not a dev and not sure how to accomplish that

**Comment by VehementHam** [comment]
I will send a screenshot of what it looks like in Netsurf with Javascript disabled. It is readable but  ugly:
![image](https://github.com/Ultramarine-Linux/wiki/assets/75701545/57df513a-3541-4fee-a407-18c3be49a1c9)

I **really** don't think that JS should be a requirement to read the site. A statement that said, "This site will look better if you enable Javascript," might be useful, but anyone disabling Javascript will already know that.

I think that it would be best to add margin to the left side of the text, or do nothing at all. I daubt that a message would help with anything.

Unless of course, the site looks worse for you when you disable Javascript.

**Comment by nothingneko** [comment]
The sidebar doesn't even work because it's pure JS, the only thing that appears to be working is the MDX rendering. This is more of a webapp

**Comment by nothingneko** [comment]
Update after chatting with the devs a bit more, this is likely a browser issue and we were able to validate it working without JS in Edge and Safari. I'm sorry for the inconvenience

**Comment by muhdsalm** [comment]
> ![image](https://github.com/Ultramarine-Linux/wiki/assets/75701545/57df513a-3541-4fee-a407-18c3be49a1c9)

Does it look weird, like @VehementHam described, or normal?

**Comment by muhdsalm** [comment]
Huh, just tested it out, and it works fine now. Maybe it is only isolated to Netsurf? It seems like an issue with CSS being blocked rather than Javascript.

**Comment by nothingneko** [comment]
Yeah, in Safari and Edge the page rendered fine. This is a browser issue, please report it there.
